rly_file = "Port_Authority_TransHudson.rly"
ttb_files = [ "PATH_MonFri_6_00.ttb",]
ssn_files = [ "PATH_Port_Authority_TransHudson_MonFri_06_00.ssn",]
img_files = [ "Port_Authority_TransHudson.bmp",]
doc_files = [ "README.md", "path-map-schedule-10-13.pdf",]
release_date = "2019-12-12"
version = "1.0.0"
country_code = "US"
factual = true
description = "Subway network connecting the east of New Jersey to the city of New York"
display_name = "Port Authority Trans-Hudson (PATH)"
name = "PATH Network"
author = "Krizar"
contributors = []
